#!/bin/bash

cd ./Software

PATH=$PATH:/usr/local/bin/ #Fix Platypus-related bug with incorrect PATH
username=`whoami`

#Start mongodb daemon if it's not running
daemonisrunning=`ps -aAc | grep mongod | wc -l | sed -e 's/^[ \t]*//'`
if [[ $daemonisrunning == "0" ]]; then
	if [[ ! -d "/Users/$username/Library/Application Support/Ardustat/mongodb" ]]; then
		mkdir ~/Library/Application\ Support/Ardustat/
		mkdir ~/Library/Application\ Support/Ardustat/mongodb/
	fi
	cd ../mongodb/
	./mongod --quiet --dbpath=/Users/$username/Library/Application\ Support/Ardustat/mongodb/&
	cd ../Software
fi

#Detect arduino device files
arduinos=`ls /dev/tty.* | grep PL2303`
numofarduinos=`ls /dev/tty.* | grep PL2303 | wc -l | sed -e 's/^[ \t]*//'`  #Number of results returned

if [[ $arduinos == "" ]]; then
	echo No Keithleys found
	exit
fi

#Start express server
if [[ $numofarduinos == "1" ]]; then
	../node expressserver.js $arduinos $1 $2 $3
	exit
fi
echo You appear to have multiple Keithleys connected. Please select one:
select fname in $arduinos;
do
	../node expressserver.js $fname $1 $2 $3
	break;
done
